"""
pydemi.data
===========
Element data shipped with pydemi (spec §15: element data live only in this
directory and in :mod:`pydemi.constants`).

``elements.csv``   Z, symbol, covalent radius (Angstrom), ground-state configuration
``free_atoms.npz`` spherical free-atom orbital densities (see :mod:`pydemi.fields.deformation`)

Both are generated by the scripts in ``tools/`` and read here without
pymatgen.
"""

from __future__ import annotations

import math
from functools import lru_cache
from pathlib import Path
from typing import Optional

DATA_DIR = Path(__file__).resolve().parent

_NOBLE_Z = (2, 10, 18, 36, 54, 86)
_L_OF = {"s": 0, "p": 1, "d": 2, "f": 3}


@lru_cache(maxsize=1)
def _table() -> dict[str, tuple[int, Optional[float], str]]:
    rows: dict[str, tuple[int, Optional[float], str]] = {}
    for line in (DATA_DIR / "elements.csv").read_text().splitlines():
        if not line or line.startswith("#") or line.startswith("Z,"):
            continue
        z, sym, radius, config = line.split(",", 3)
        rows[sym] = (int(z), float(radius) if radius else None, config)
    return rows


def _row(symbol: str) -> tuple[int, Optional[float], str]:
    try:
        return _table()[symbol]
    except KeyError:
        raise KeyError(f"unknown element {symbol!r}") from None


def atomic_number(symbol: str) -> int:
    return _row(symbol)[0]


def symbol_of(z: int) -> str:
    for sym, (zz, _, _) in _table().items():
        if zz == int(z):
            return sym
    raise KeyError(f"no element with Z = {z}")


def covalent_radius(symbol: str) -> float:
    """Covalent radius in Angstrom (Cordero et al. 2008, via Magpie)."""
    r = _row(symbol)[1]
    if r is None:
        raise KeyError(f"no covalent radius for {symbol!r}")
    return r


def configuration(symbol: str) -> list[tuple[int, int, float]]:
    """Ground-state configuration as (n, l, occupation) triples."""
    out = []
    for token in _row(symbol)[2].split():
        n, l, occ = int(token[0]), _L_OF[token[1]], float(token[2:])
        out.append((n, l, occ))
    return out


def default_zval(symbol: str) -> float:
    """Valence electrons of the standard VASP PAW dataset, from the configuration alone.

    Electrons outside the preceding noble-gas core, minus a filled f14 shell
    and, for the p-block (valence p electrons present), minus the filled
    (n-1)d10 shell: Ga -> 3, Sn -> 4, Sb -> 5, Bi -> 5; Zn keeps its 3d10
    (12). Lanthanides and actinides keep the core's outer s2 p6 and their f
    shell, as the standard datasets do: La -> 11, Er -> 22, Lu -> 25, U -> 14.
    A last resort -- the semicore datasets of the s-block and early d-block
    (K_pv or K_sv, Ca_pv or Ca_sv, Y_sv, Zr_sv, Nb_pv, ...) are a per-run
    choice, so read ZVAL from the POTCAR or OUTCAR, or pass a table
    (``read_vasp(..., zval=...)``), whenever the run used such datasets.
    """
    z = atomic_number(symbol)
    core_z = max((n for n in _NOBLE_Z if n < z), default=0)
    core = set() if core_z == 0 else {(n, l) for n, l, _ in configuration(symbol_of(core_z))}
    shells = [(n, l, occ) for n, l, occ in configuration(symbol) if (n, l) not in core]
    n_top = max((n for n, l, _ in shells if l <= 1), default=0)
    p_block = any(l == 1 and n == n_top and occ > 0 for n, l, occ in shells)
    if 57 <= z <= 71 or 89 <= z <= 103:
        return float(sum(occ for _, _, occ in shells) + 8)
    val = sum(occ for n, l, occ in shells
              if not (l == 3 and math.isclose(occ, 14.0))
              and not (p_block and l == 2 and n == n_top - 1 and math.isclose(occ, 10.0)))
    return float(val)
