"""
Generate ``src/pydemi/data/elements.csv`` (development-time tool; needs pymatgen).

Columns
-------
Z, symbol          atomic number and element symbol
covalent_radius    Angstrom; Magpie "CovalentRadius" (Cordero et al., Dalton
                   Trans. 2832 (2008)) as distributed with matminer 0.10.1
                   (BSD licence, see src/pydemi/data/LICENSE-matminer); empty
                   where the source has no value
configuration      ground-state configuration, e.g. "1s2 2s2 2p6 3s2 3p6 3d6 4s2"
                   (pymatgen ``Element.full_electronic_structure``)

pydemi reads this table at run time instead of importing pymatgen, so the
numerical core depends only on numpy and scipy.

Usage:  python tools/generate_element_data.py
"""

from pathlib import Path

from pymatgen.core import Element

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools" / "magpie_elements_source.csv"
OUT = ROOT / "src" / "pydemi" / "data" / "elements.csv"
Z_MAX = 103


def magpie_covalent_radii() -> dict:
    lines = [l for l in SOURCE.read_text().splitlines() if not l.startswith("#")]
    header = lines[0].split(",")
    col = header.index("CovalentRadius")
    out = {}
    for row in lines[1:]:
        cells = row.split(",")
        value = cells[col]
        out[int(cells[0])] = None if value == "nan" else float(value) / 100.0   # pm -> Angstrom
    return out


def main() -> None:
    radii = magpie_covalent_radii()
    rows = ["# Element data for pydemi, generated by tools/generate_element_data.py.",
            "# covalent_radius: Angstrom (Magpie / Cordero 2008, BSD licence, see LICENSE-matminer).",
            "# configuration: ground state (pymatgen). Empty cell = no value in the source.",
            "Z,symbol,covalent_radius,configuration"]
    for z in range(1, Z_MAX + 1):
        el = Element.from_Z(z)
        config = " ".join(f"{n}{l}{int(f) if float(f).is_integer() else f}"
                          for n, l, f in el.full_electronic_structure)
        r = radii.get(z)
        rows.append(f"{z},{el.symbol},{'' if r is None else f'{r:.2f}'},{config}")
    OUT.write_text("\n".join(rows) + "\n")
    print(f"wrote {OUT} ({Z_MAX} elements)")


if __name__ == "__main__":
    main()
